import {describe,it,expect} from 'vitest';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import app from '../server/index';
import type {Database,Statement} from '../server/database';
function setup(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync('drizzle/0000_daffy_chimera.sql','utf8'));sql.exec(readFileSync('drizzle/0001_careful_hitman.sql','utf8'));const db:Database={prepare(query:string){let values:any[]=[];const s:Statement={bind(...v){values=v;return s;},async first<T>(){return (sql.prepare(query).get(...values)||null) as T|null;},async all<T>(){return {results:sql.prepare(query).all(...values) as T[]};},async run(){return sql.prepare(query).run(...values);}};return s;},async batch(statements){return Promise.all(statements.map(s=>s.run()));}};return {sql,env:{DB:db,ASSETS:{fetch:async()=>new Response('')}}};}
const wallet='0x1111111111111111111111111111111111111111',id='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
const post=(body:unknown)=>new Request('https://test/api/leaderboard',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
describe('wallet scores',()=>{
 it('validates wallet, persists payout address, and prevents changing submitted identity',async()=>{const {sql,env}=setup();sql.prepare("INSERT INTO runs(id,started_at,outcome,elapsed_ms,finished_at) VALUES(?,?,'complete',5000,?)").run(id,Date.now()-6000,Date.now());expect((await app.fetch(post({id,name:'Slayer',wallet:'bad'}),env)).status).toBe(400);expect((await app.fetch(post({id,name:'Slayer',wallet}),env)).status).toBe(200);expect(sql.prepare('SELECT wallet_address FROM runs').get()?.wallet_address).toBe(wallet);expect((await app.fetch(post({id,name:'Slayer',wallet}),env)).status).toBe(200);expect((await app.fetch(post({id,name:'Other',wallet}),env)).status).toBe(409);sql.close();});
 it('searches all historical scores without exposing payout addresses',async()=>{const {sql,env}=setup();const insert=sql.prepare("INSERT INTO runs(id,started_at,outcome,elapsed_ms,finished_at,player_name,wallet_address) VALUES(?,0,'complete',?,?,?,?)");insert.run('old',3000,Date.now()-86400000,'Slayer',wallet);insert.run('new',5000,Date.now(),'Slayer',wallet);for(const q of ['slayer',wallet]){const r=await (await app.fetch(new Request('https://test/api/player-scores?q='+q),env)).json();expect(r.total).toBe(2);expect(r.bestMs).toBe(3000);expect(r.entries.map((e:any)=>e.elapsedMs)).toEqual([3000,5000]);expect(JSON.stringify(r)).not.toContain(wallet);expect(r.entries.map((e:any)=>e.walletShort)).toEqual(['0x1111…1111','0x1111…1111']);expect(r.entries.every((e:any)=>!('wallet' in e))).toBe(true);}const daily=await (await app.fetch(new Request('https://test/api/leaderboard'),env)).json();expect(daily.entries).toHaveLength(1);expect(JSON.stringify(daily)).not.toContain(wallet);expect(daily.entries[0].walletShort).toBe('0x1111…1111');const miss=await (await app.fetch(new Request('https://test/api/player-scores?q=missing'),env)).json();expect(miss.total).toBe(0);expect(miss.bestMs).toBeNull();sql.close();});
});
