import {useEffect,useState} from 'react';
import {formatTime} from '../../shared/round';
import {ShareRound} from './share';
export async function scoreApi<T>(path:string,body?:unknown,signal?:AbortSignal):Promise<T>{
 const response=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:signal?AbortSignal.any([signal,AbortSignal.timeout(10000)]):AbortSignal.timeout(10000)});
 const data=await response.json().catch(()=>({error:'Leaderboard unavailable. Please try again.'}));
 if(!response.ok)throw new Error(data.error||'Could not save your time. Please try again.');
 return data as T;
}
type Entry={name:string;wallet:string|null;elapsedMs:number;finishedAt:number};
export function WalletAddress({wallet}:{wallet:string|null}){return wallet?<details className="score-wallet"><summary>{wallet.slice(0,6)}…{wallet.slice(-4)}</summary><code>{wallet}</code></details>:<small className="legacy-wallet">No wallet submitted</small>;}
export function PlayerScores({revision}:{revision:number}){
 const [input,setInput]=useState(()=>{try{return localStorage.getItem('doom-player-wallet')||'';}catch{return '';}}),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[data,setData]=useState<{entries:Entry[];total:number;bestMs:number|null}>(),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{if(!query)return;const controller=new AbortController();setLoading(true);setError('');void scoreApi<{entries:Entry[];total:number;bestMs:number|null}>(`/api/player-scores?q=${encodeURIComponent(query)}&offset=${offset}`,undefined,controller.signal).then(setData).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[query,offset,revision]);
 return <section className="player-scores" aria-labelledby="player-scores-title"><h3 id="player-scores-title">FIND YOUR BEST RUN</h3><form onSubmit={e=>{e.preventDefault();setOffset(0);setQuery(input.trim());}}><label htmlFor="score-search">Player name or full wallet address</label><div><input id="score-search" type="search" minLength={2} maxLength={42} required value={input} onChange={e=>setInput(e.target.value)} placeholder="Username or 0x…"/><button type="submit">FIND SCORES</button></div></form><p className="ranking-note">All-time submitted scores, fastest first. Names are not unique; search by wallet for a more specific match.</p>{loading?<p role="status">Finding scores…</p>:error?<p role="alert">{error}</p>:data&&<><div className="personal-best"><span>PERSONAL BEST <b>{data.bestMs===null?'—':formatTime(data.bestMs)}</b></span><span>{data.total} COMPLETED RUN{data.total===1?'':'S'}</span></div>{data.entries.length===0?<p>No submitted scores found.</p>:<div className="ranking-scroll"><table><thead><tr><th>PLAYER / WALLET</th><th>TIME</th><th>FINISHED (UTC)</th></tr></thead><tbody>{data.entries.map((entry,i)=><tr key={`${entry.finishedAt}-${i}`}><td>{entry.name}<WalletAddress wallet={entry.wallet}/></td><td><time>{formatTime(entry.elapsedMs)}</time></td><td>{new Date(entry.finishedAt).toISOString().slice(0,16).replace('T',' ')}</td></tr>)}</tbody></table></div>}<div className="score-pages">{offset>0&&<button onClick={()=>setOffset(Math.max(0,offset-50))}>PREVIOUS</button>}{offset+50<data.total&&<button onClick={()=>setOffset(offset+50)}>NEXT 50</button>}</div></>}</section>;
}
const medals=[{tone:'gold',label:'Gold DOOM medal',share:'60%'},{tone:'silver',label:'Silver DOOM medal',share:'20%'},{tone:'bronze',label:'Bronze DOOM medal',share:'10%'}] as const;
export function Leaderboard({revision}:{revision:number}){
 const [entries,setEntries]=useState<Entry[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{
  const controller=new AbortController();let busy=false;
  async function load(){if(busy)return;busy=true;try{const result=await scoreApi<{entries:Entry[]}>('/api/leaderboard',undefined,controller.signal);if(!controller.signal.aborted){setEntries(result.entries);setError('');}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Could not load rankings.');}finally{busy=false;if(!controller.signal.aborted)setLoading(false);}}
  void load();const timer=setInterval(()=>{if(!document.hidden)void load();},30000);
  return()=>{controller.abort();clearInterval(timer);};
 },[revision,retry]);
 return <section className="leaderboard" id="leaderboard" aria-labelledby="leaderboard-title">
  <div className="leaderboard-heading"><div><p className="eyebrow">TODAY // UTC PRIZE ROUND</p><h2 id="leaderboard-title">TODAY'S FASTEST FINISHES</h2></div><div className="leaderboard-actions"><ShareRound/><button onClick={()=>setRetry(x=>x+1)}>REFRESH</button></div></div>
  <div className="daily-pot" aria-label="Daily prize distribution"><div><strong>DAILY TRADING FEE POT</strong><span>Awarded every day at 00:00 UTC</span></div><ol>{medals.map((medal,i)=><li className={medal.tone} key={medal.tone}><span className={`doom-medal ${medal.tone}`} aria-hidden="true"><img src="/doom-pixel-medal.png" alt=""/></span><b>{i+1}{i===0?'ST':i===1?'ND':'RD'}</b><strong>{medal.share}</strong></li>)}</ol><p className="pot-rollover"><strong>10% ROLLS OVER</strong><span>Recycled into the next day’s prize pool</span></p></div>
  <p className="ranking-note">Reach the exit, enter your name and payout wallet, and post your time. Today's three fastest finishers share the pot: 1st wins 60%, 2nd wins 20%, and 3rd wins 10%. The remaining 10% rolls into the next day’s prize pool. Rankings reset at 00:00 UTC.</p>
  {loading?<p role="status">Loading rankings…</p>:error?<div className="ranking-error" role="alert">{error} <button onClick={()=>setRetry(x=>x+1)}>TRY AGAIN</button></div>:entries.length===0?<div className="ranking-empty">NO FINISHERS YET.<span>Be the first to make it out.</span></div>:<div className="ranking-scroll"><table><thead><tr><th scope="col">RANK</th><th scope="col">PLAYER</th><th scope="col">ROUND TIME</th><th scope="col"><span className="sr-only">Share round</span></th></tr></thead><tbody>{entries.map((entry,i)=>{const medal=medals[i];return <tr className={medal?'podium-row '+medal.tone:''} key={`${entry.finishedAt}-${i}`}><td><span className="rank-number">{String(i+1).padStart(2,'0')}</span>{medal&&<span className={`doom-medal ${medal.tone}`} title={medal.label}><img src="/doom-pixel-medal.png" alt=""/><span className="sr-only">{medal.label}</span></span>}</td><td>{entry.name}<WalletAddress wallet={entry.wallet}/></td><td className="round-time"><time>{formatTime(entry.elapsedMs)}</time></td><td><ShareRound elapsedMs={entry.elapsedMs} name={entry.name} compact/></td></tr>})}</tbody></table></div>}
  <PlayerScores revision={revision}/>
 </section>;
}
